const speciesData = 
[
  {
    "image": "https://www.monumentaltrees.com/db/39/600/39518.jpg",
    "province": "Granada",
    "municipality": "Baza",
    "averageAltitude": 800,
    "biogeographicSector": "Granadino",
    "bioclimaticFloor": "Meso",
    "ombrotype": "húmedo",
    "natureOfSubstrate": "Básico",
    "serieType": "Orofito.",
    "vegetationSeries": "Pm-Pc",
    "potentialVegetation": "Pinar",
    "scientificName": "Pinus sylvestris"
  },
  {
    "image": "https://media.jardineriadelvalles.com/product/higuera-ficus-carica-brown-turkey-800x800.jpg",
    "province": "Jaén",
    "municipality": "Andújar",
    "averageAltitude": 600,
    "biogeographicSector": "Bético",
    "bioclimaticFloor": "Meso",
    "ombrotype": "subhúmedo",
    "natureOfSubstrate": "Yesos",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qf-Qc",
    "potentialVegetation": "Encinar",
    "scientificName": "Ficus carica"
  },
  {
    "image": "https://static.inaturalist.org/photos/87326219/large.jpg",
    "province": "Málaga",
    "municipality": "Antequera",
    "averageAltitude": 450,
    "biogeographicSector": "Malacitano",
    "bioclimaticFloor": "Termo",
    "ombrotype": "semiárido",
    "natureOfSubstrate": "Calcáreo",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qu-Qf",
    "potentialVegetation": "Matorral",
    "scientificName": "Rosmarinus officinalis"
  },
  {
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/ac/Den_Italienske_Sti%2C_eneb%C3%A6r.JPG",
    "province": "Cádiz",
    "municipality": "Tarifa",
    "averageAltitude": 100,
    "biogeographicSector": "Gaditano",
    "bioclimaticFloor": "Termo",
    "ombrotype": "húmedo",
    "natureOfSubstrate": "Arcilloso",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qu-Qc",
    "potentialVegetation": "Matorral",
    "scientificName": "Juniperus communis"
  },
  {
    "image": "https://www.thecolvinco.com/blog/wp-content/uploads/2018/10/shutterstock_118541248.jpg",
    "province": "Córdoba",
    "municipality": "Priego de Córdoba",
    "averageAltitude": 700,
    "biogeographicSector": "Cordobés",
    "bioclimaticFloor": "Supramedit.",
    "ombrotype": "subhúmedo",
    "natureOfSubstrate": "Silíceo",
    "serieType": "Orofito.",
    "vegetationSeries": "Qf-Rl",
    "potentialVegetation": "Encinar",
    "scientificName": "Cistus ladanifer"
  },
  {
    "image": "https://inaturalist-open-data.s3.amazonaws.com/photos/13488403/original.jpeg",
    "province": "Sevilla",
    "municipality": "Écija",
    "averageAltitude": 150,
    "biogeographicSector": "Sevillano",
    "bioclimaticFloor": "Termo",
    "ombrotype": "semiárido",
    "natureOfSubstrate": "Calcáreo",
    "serieType": "Climatóf.",
    "vegetationSeries": "Ol-Qc",
    "potentialVegetation": "Olivar",
    "scientificName": "Cyperus papyrus"
  },
  {
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/85/Carrasca_de_la_Raboseras.JPG",
    "province": "Huelva",
    "municipality": "Aracena",
    "averageAltitude": 400,
    "biogeographicSector": "Onubense",
    "bioclimaticFloor": "Meso",
    "ombrotype": "húmedo",
    "natureOfSubstrate": "Silíceo",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qc-Qf",
    "potentialVegetation": "Alcornocal",
    "scientificName": "Quercus ilex"
  },
  {
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Pinus_pinea_Wellington_Botanic_Gardens.jpg",
    "province": "Almería",
    "municipality": "Níjar",
    "averageAltitude": 20,
    "biogeographicSector": "Almeriense",
    "bioclimaticFloor": "Termo",
    "ombrotype": "árido",
    "natureOfSubstrate": "Yesos",
    "serieType": "Climatóf.",
    "vegetationSeries": "Ql-Pc",
    "potentialVegetation": "Pinar",
    "scientificName": "Pinus pinea"
  },
  {
    "image": "https://www.floresyplantas.net/wp-content/uploads/flores-de-bougainvillea-alexandra.jpg",
    "province": "Granada",
    "municipality": "Almuñécar",
    "averageAltitude": 30,
    "biogeographicSector": "Granadino",
    "bioclimaticFloor": "Termo",
    "ombrotype": "húmedo",
    "natureOfSubstrate": "Calcáreo",
    "serieType": "Orofito.",
    "vegetationSeries": "Pm-Qf",
    "potentialVegetation": "Pinar",
    "scientificName": "Bougainvillea glabra"
  },
  {
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/43/Vitis_vinifera_001.jpg",
    "province": "Jaén",
    "municipality": "Úbeda",
    "averageAltitude": 750,
    "biogeographicSector": "Bético",
    "bioclimaticFloor": "Meso",
    "ombrotype": "subhúmedo",
    "natureOfSubstrate": "Yesos",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qf-Rl",
    "potentialVegetation": "Viñedo",
    "scientificName": "Vitis vinifera"
  },
  {
    "image": "https://media.plantamus.com/c/product/fresno-comun-fresno-negro-freixo-fraxinus-excelsior-520x520_3bgRUS5.jpg",
    "province": "Málaga",
    "municipality": "Ronda",
    "averageAltitude": 720,
    "biogeographicSector": "Malacitano",
    "bioclimaticFloor": "Supramedit.",
    "ombrotype": "semiárido",
    "natureOfSubstrate": "Ácido",
    "serieType": "Orofito.",
    "vegetationSeries": "Rl-Qc",
    "potentialVegetation": "Fresneda",
    "scientificName": "Fraxinus excelsior"
  },
  {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Populus_nigra-bekes.jpg/250px-Populus_nigra-bekes.jpg",
    "province": "Sevilla",
    "municipality": "Cazalla de la Sierra",
    "averageAltitude": 450,
    "biogeographicSector": "Sevillano",
    "bioclimaticFloor": "Meso",
    "ombrotype": "húmedo",
    "natureOfSubstrate": "Silíceo",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qc-Qf",
    "potentialVegetation": "Alcornocal",
    "scientificName": "Populus nigra"
  },
  {
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Eucalyptus_tereticornis_flowers%2C_capsules%2C_buds_and_foliage.jpeg",
    "province": "Cádiz",
    "municipality": "San Fernando",
    "averageAltitude": 15,
    "biogeographicSector": "Gaditano",
    "bioclimaticFloor": "Termo",
    "ombrotype": "húmedo",
    "natureOfSubstrate": "Arcilloso",
    "serieType": "Climatóf.",
    "vegetationSeries": "Qu-Qc",
    "potentialVegetation": "Eucaliptal",
    "scientificName": "Eucalyptus globulus"
  },
  {
    "image": "https://media.plantamus.com/c/product/arce-japones-crimson-queen-acer-palmatum-crimson-queen-520x520_wxjdJAd.jpg",
    "province": "Córdoba",
    "municipality": "Priego de Córdoba",
    "averageAltitude": 700,
    "biogeographicSector": "Cordobés",
    "bioclimaticFloor": "Supramedit.",
    "ombrotype": "subhúmedo",
    "natureOfSubstrate": "Silíceo",
    "serieType": "Orofito.",
    "vegetationSeries": "Qf-Rl",
    "potentialVegetation": "Arce",
    "scientificName": "Acer palmatum"
  }
]
;
  
  export default speciesData;